version: "3.1"
services:
  mysql-dev:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    ports:
      - 3306:3306
    volumes:
      - mysql-dev:/tmp

volumes:
  mysql-dev:
    external: false